spring:
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
logging.level.org.hibernate.SQL: INFO

springdoc:
 api-docs:
  version: OPENAPI_3_1
  path: /v1/api-docs
 swagger-ui:
  path: /swagger-ui.html